pipeline {
  agent any
  environment {
    IMAGE_NAME = "backend_app"
    COMPOSE_DIR = "backend" // docker-compose.yml 경로
  }

  options {
    skipDefaultCheckout(true)
  }

  triggers {
    gerrit(
      serverName: 'gerrit',
      gerritProjects: [[
        compareType: 'PLAIN',
        pattern: 'S13P11E108',
        branches: [[compareType: 'PLAIN', pattern: 'master']]
      ]],
      triggerOnEvents: [
        changeMerged(), // Gerrit에서 승인되어 머지된 경우만 실행
      ]
    )
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build') {
      steps {
        dir("${COMPOSE_DIR}") {
            sh 'chmod +x ./gradlew'
            // sh './gradlew clean build'
            sh './gradlew clean build -x test'  // ✅ test 제외
        }
      }
    }

    stage('Test') {
      steps {
        dir("${COMPOSE_DIR}") {
          // 테스트 수행 단계 (필요시 주석 해제)
          // sh './gradlew test'
        }
      }
    }

    stage('Docker Compose Rebuild') {
      steps {
        dir("${COMPOSE_DIR}") {
          withCredentials([
            string(credentialsId: 'DB_USER', variable: 'DB_USER'),
            string(credentialsId: 'DB_PASS', variable: 'DB_PASS'),
            string(credentialsId: 'JWT_SECRET', variable: 'JWT_SECRET')
          ]) {
            withEnv([
              "SPRING_DATASOURCE_USERNAME=$DB_USER",
              "SPRING_DATASOURCE_PASSWORD=$DB_PASS",
              "MYSQL_DATABASE=tetonam",
              "JWT_SECRET=$JWT_SECRET"
            ]) {
              sh 'docker-compose down'
              sh 'docker-compose up -d --build'
            }
          }
        }
      }
    }

    stage('Docker Image Push') {
      steps {
        dir("${COMPOSE_DIR}") {
          withCredentials([
            usernamePassword(
              credentialsId: 'dockerhub-creds',
              usernameVariable: 'DOCKER_USER',
              passwordVariable: 'DOCKER_PASS'
            )
          ]) {
            script {
              def imageName = "${IMAGE_NAME}:latest"
              def dockerHubRepo = "${DOCKER_USER}/${IMAGE_NAME}:latest"

              // 빌드 및 DockerHub로 푸시
              sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
              sh "docker build -t ${imageName} ."
              sh "docker tag ${imageName} ${dockerHubRepo}"
              sh "docker push ${dockerHubRepo}"
            }
          }
        }
      }
    }
  }

  post {
    success {
      echo "✅ 배포 성공: $IMAGE_NAME has been built and deployed."
    }
    failure {
      echo "❌ 배포 실패: 오류가 발생했습니다!"
    }
  }
}
