pipeline {
  agent any
  environment {
    IMAGE_NAME = "backend_app"
    COMPOSE_DIR = "backend" // docker-compose.yml 경로
  }

  options {
    skipDefaultCheckout(true)
  }

  triggers {
    gerrit(
      serverName: 'gerrit',
      gerritProjects: [[
        compareType: 'PLAIN',
        pattern: 'S13P11E108',
        branches: [[compareType: 'PLAIN', pattern: 'master']]
      ]],
      triggerOnEvents: [
        changeMerged(), // Gerrit에서 승인되어 머지된 경우만 실행
      ]
    )
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build') {
      steps {
        dir('backend') {
            sh 'chmod +x ./gradlew'
            sh './gradlew clean build'
        }
      }
    }

    stage('Test') {
      steps {
        dir('backend') {
          // 테스트 수행 단계 (필요시 주석 해제)
          // sh './gradlew test'
        }
      }
    }

    stage('Docker Compose Rebuild') {
      steps {
        dir("${COMPOSE_DIR}") {
          sh 'docker-compose down'
          sh 'docker-compose build'
          sh 'docker-compose up -d'
        }
      }
    }
  }

  post {
    success {
      echo "✅ 배포 성공: $IMAGE_NAME has been built and deployed."
    }
    failure {
      echo "❌ 배포 실패: 오류가 발생했습니다!"
    }
  }
}
